### ISSUE TITLE
Excelente

### ISSUE THREAD

**Issue by eduardo-cubos** [brandaoti/desafio003#1]
Parabéns Daniel. Excelente Design, tentou outras coisas.

Seu componente ficou muito bom.
Dá uma olhada na resolução do exercício na plataforma pra vê com usar as closures, dessa forma você pode simplificar um pouco o uso de setState.

**Comment by brandaoti** [comment]
@eduardo-cubos 
Obrigado professor. Ainda não vi a resolução dos exercícios, mas pegando a base do bate-papo que tivemos, consegui entender um pouco mais como funciona o uso das **closures**.   
Irei da uma olhada na resolução para entender mais da explicação. :full_moon_with_face:
